### ISSUE TITLE
update minimum go version

### ISSUE THREAD

**Issue by shinenelson** [github/hub#3369]
I was attempting to compile go from source using the latest HEAD. But I could not get the compilation to complete because it required a minimum version higher than the one specified in `go.mod`.

https://github.com/mislav/hub/blob/5c547ed804368763064e51f3990851e267e88edd/go.mod#L3

`go mod` specifies `go1.11` as the version that the source builds on, but while attempting a build, it fails. I was attempting a build using `go1.14` which was higher than the minimum version. Using `go1.17` resolved the error and completed the build successfully.

**Command attempted:**
`make bin/hub`

**What happened:**
```
/home/shine/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
/home/shine/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_linux.go:2271:9: undefined: unsafe.Slice
/home/shine/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
/home/shine/go/pkg/mod/golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
make: *** [Makefile:51: bin/hub] Error 2
```

**Steps to Reproduce**
use any go version < go1.17.
1. `git clone https://github.com/mislav/hub`
2. `make bin/hub`

I can create a pull request if this is a valid bug and the version in `go.mod` needs updating.

**Comment by shinenelson** [comment]
`git bisect` identified #3259 as the _first bad commit_ for `go1.17`.

PS : I was attempting to build using `go1.14` on 5c547ed. I am not sure whether there are other commits that raise the required version between `go1.11` and `go1.14`.
